packages:
  - .
  - apps/*
catalogs:
  repo:
    nuxt: 4.4.2
    superjson: ^2.2.6
    zod: ^3.25.76
  trpc:
    '@trpc/client': ^11.12.0
    '@trpc/server': ^11.12.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - sharp
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
