packages:
  - .
  - apps/*
catalogs:
  repo:
    nuxt: 4.4.5
    superjson: ^2.2.6
    zod: ^3.25.76
  trpc:
    '@trpc/client': ^11.17.0
    '@trpc/server': ^11.17.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
