packages:
  - .
  - apps/*
catalogs:
  repo:
    nuxt: 4.1.3
    superjson: ^2.2.2
    zod: ^3.24.2
  trpc:
    '@trpc/client': ^11.6.0
    '@trpc/server': ^11.6.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - sharp
