packages:
  - .
  - apps/*
catalogs:
  repo:
    nuxt: 4.1.3
    superjson: ^2.2.6
    zod: ^3.25.76
  trpc:
    '@trpc/client': ^11.8.0
    '@trpc/server': ^11.8.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - sharp
