import { dirname, resolve } from 'path'
import { defineNuxtModule } from '@nuxt/kit'
import fs from 'fs-extra'

export interface ModuleOptions {}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'trpc-nuxt',
    configKey: 'trpc',
  },
  defaults: {},
  async setup(_options, nuxt) {
    const root = nuxt.options.rootDir
    const apiPath = resolve(root, 'server/api/trpc/[query].ts')

    await fs.ensureDir(dirname(apiPath))
    await fs.writeFile(apiPath, `
      // generated by trpc-nuxt
      import { createTRPCHandler } from 'trpc-nuxt/handler'
      import * as functions from '../../fn'
      export default createTRPCHandler({
        router: functions.router
      })
    `.trimStart())
  },
})
