// generated by trpc-nuxt
      import { createTRPCHandler } from 'trpc-nuxt/handler'
      import * as functions from '../../fn'
      export default createTRPCHandler({
        router: functions.router
      })
    